# Example values for Metashot
# Copy this file and customize it for your deployment

# Required environment variables
env:
  METABASE_SITE_URL: "https://metabase.example.com"
  S3_BUCKET: "my-metashot-bucket"
  S3_REGION: "us-east-1"
  S3_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"

# Use secrets for sensitive values
envFrom:
  - secretRef:
      name: metashot-secrets

# Enable ingress for external access
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: metashot.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: metashot-tls
      hosts:
        - metashot.example.com

# Configure resources based on your needs
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Enable autoscaling if needed
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
